[build]
  command = "curl https://sh.rustup.rs -sSf | sh -s -- -y && source $HOME/.cargo/env && cargo install wasm-pack && cd reader && wasm-pack build --target web && cd .. && npm run build"
  publish = "dist"
